(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&c(r)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const i=[{name:"Jane Cooper",company:"Microsoft",phone:"(225) 555-0118",email:"jane@microsoft.com",country:"United States",status:"Active"},{name:"Floyd Miles",company:"Yahoo",phone:"(205) 555-0100",email:"floyd@yahoo.com",country:"Kiribati",status:"Inactive"},{name:"Ronald Richards",company:"Adobe",phone:"(302) 555-0107",email:"ronald@adobe.com",country:"Israel",status:"Inactive"},{name:"Marvin McKinney",company:"Tesla",phone:"(252) 555-0126",email:"marvin@tesla.com",country:"Iran",status:"Active"},{name:"Jerome Bell",company:"Google",phone:"(629) 555-0129",email:"jerome@google.com",country:"Réunion",status:"Active"},{name:"Kathryn Murphy",company:"Microsoft",phone:"(406) 555-0120",email:"kathryn@microsoft.com",country:"Curaçao",status:"Active"},{name:"Jacob Jones",company:"Yahoo",phone:"(208) 555-0112",email:"jacob@yahoo.com",country:"Brazil",status:"Active"},{name:"Kristin Watson",company:"Facebook",phone:"(704) 555-0127",email:"kristin@facebook.com",country:"Åland Islands",status:"Inactive"}],d=document.querySelector(".dashboard__close-btn"),l=document.querySelector(".dashboard__header-btn"),a=document.querySelector(".dashboard__menu-container");l.addEventListener("click",()=>a.classList.add("is-open"));d.addEventListener("click",()=>a.classList.remove("is-open"));a.addEventListener("click",()=>a.classList.remove("is-open"));const m=n=>n.reduce((s,t)=>s+`
      <tr class="customers__container-table-rows">
      <td>${t.name}</td>
      <td>${t.company}</td>
      <td>${t.phone}</td>
      <td>${t.email}</td>
      <td>${t.country}</td>
      <td><span class="status ${t.status.toLowerCase()}">${t.status}</span></td>
      </tr>
      `,""),u=n=>{const s=document.querySelector(".customers__container-table tbody");s.innerHTML=m(n)};document.addEventListener("DOMContentLoaded",()=>{u(i);const n=document.querySelector(".dashboard__logo-icon");setTimeout(()=>{n.style.opacity="1",n.style.transform="scale(1)",n.style.animation="rotate 2000ms linear 1"},250)});document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".customers__container-table-rows").forEach((s,t)=>{setTimeout(()=>{s.classList.add("visible")},t*100)})});
//# sourceMappingURL=commonHelpers.js.map
